Repository Seoul-Public-Data/seoul_frontend, pull requests merged in 2024-04, with the labels that each got.

#8 feat: kakao map api 연동
  .gitignore
  public/index.html
  src/App.tsx
Labels: feat

#12 Chore : react router dom install 및 설정
  package-lock.json
  package.json
  src/App.tsx
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
Labels: chore

#14 feat : 신고지도페이지 마커 표시 및 영역 표시 기능
  src/pages/EmergencyPage.tsx
Labels: feat

#15 feat: 카카오 지도 위에 안전시설 마커 표시
  .eslintrc.json
  src/assets/images/cctv.png
  src/assets/images/emergencybell.png
  src/assets/images/firestation.png
  src/assets/images/heatshelter.png
  src/assets/images/location.png
  src/assets/images/safetycenter.png
  src/assets/images/safetyfacility.png
  src/pages/Home.tsx
Labels: style, feat

#17 feat: 현 위치 좌표를 도로명 주소로 변환, 키워드 장소 검색
  src/hooks/usePlaceSearch.ts
  src/pages/Home.tsx
Labels: feat

#19 refactor : 지도 관련 로직 리팩터링
  src/components/SearchInput.tsx
  src/constant/mockingPositions.ts
  src/hooks/useCurruntPosition.ts
  src/hooks/useMap.ts
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: refactor

#20 refactor : useMap 관련 수정사항 변경
  src/hooks/useMap.ts
Labels: refactor

#24 fix : useMap 의존성 관련 문제 해결
  src/hooks/useCurruntPosition.ts
  src/hooks/useMap.ts
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/utils/mapUtils.ts
Labels: fix

#25 feat: 카카오 지도에 다중 경유지 경로 표시
  .eslintrc.json
  src/assets/images/way.png
  src/components/SearchInput.tsx
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: feat

#28 feat : Bottom Sheet 마우스 이벤트 추가
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/constant/bottomSheetPosition.ts
  src/hooks/useBottomSheet.ts
  src/hooks/useBottomSheetTouch.ts
Labels: feat

#31 feat: 티맵 api로 전환
  public/index.html
  src/components/SearchInput.tsx
  src/constant/mockingPositions.ts
  src/hooks/useMap.ts
  src/hooks/usePlaceSearch.ts
  src/index.tsx
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: feat, fix

#34 feat : 원 그리기 기능, 인포 윈도우 생성 기능 추가
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/utils/mapUtils.ts
Labels: feat

#36 fix : BottomSheet 관련 오류 해결
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetContents/style.ts
Labels: fix

#38 feat: 보행자 경로안내로 변경 및 출발, 도착, 경유지 마커 표시
  src/assets/images/ep.png
  src/assets/images/pp.png
  src/assets/images/sp.png
  src/pages/Home.tsx
  src/utils/mapUtils.ts
Labels: feat

#42 design : 신고 리스트 UI 구현
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetContents/style.ts
  src/components/ReportList/index.tsx
  src/components/ReportList/style.ts
  src/constant/mockingTimeStamp.ts
  src/pages/EmergencyPage.tsx
Labels: design

#45 feat : BottomSheet 터치 안되는 이슈 해결 및 신고리스트 기능 추가
  public/reset.css
  src/App.tsx
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetContents/style.ts
  src/components/BottomSheetHeader/style.ts
  src/components/ReportList/index.tsx
  src/constant/mockingTimeStamp.ts
  src/hooks/useBottomSheet.ts
  src/hooks/useMap.ts
  src/pages/EmergencyPage.tsx
  src/utils/mapUtils.ts
Labels: feat, fix

#47 fix: 새로운 경로 탐색시 이전 경로, 마커 지우도록 수정
  src/pages/Home.tsx
  src/utils/mapUtils.ts
Labels: fix

#48 feat : BottomSheet 필터링 기능 추가
  src/App.tsx
  src/components/BottomSheet/index.tsx
  src/components/BottomSheetContents/index.tsx
  src/constant/mockingPositions.ts
  src/hooks/useFilteringMarker.ts
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/recoil/atoms.ts
  src/utils/mapUtils.ts
Labels: feat

#55 Feat/draw multi route
  src/pages/RouteExplorer.tsx
  src/utils/mapUtils.ts
Labels: feat

#60 design: 경로에 대한 간단한 정보를 보여주는 UI 구현
  public/reset.css
  src/assets/images/danger.svg
  src/components/RouteCarousel/index.tsx
  src/components/RouteCarousel/style.ts
  src/pages/RouteExplorer.tsx
  src/utils/mapUtils.ts
Labels: design

#61 feat : 안전시설 필터링 기능 구현 및 API와 연결
  src/components/BottomSheetContents/index.tsx
  src/constant/mockingPositions.ts
  src/hooks/useFilteringMarker.ts
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/recoil/atoms.ts
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: feat

#63 design: 모바일 사이즈 공통 Wrapper 적용
  public/reset.css
  src/components/BottomSheet/style.ts
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetContents/style.ts
  src/components/BottomSheetHeader/style.ts
  src/components/RouteCarousel/style.ts
  src/components/Search/index.tsx
  src/components/Search/style.ts
  src/components/common/Wrapper/index.tsx
  src/components/common/Wrapper/style.ts
  src/constant/bottomSheetPosition.ts
  src/hooks/useMap.ts
  src/pages/EmergencyPage.tsx
  src/pages/Home.tsx
  src/pages/RouteExplorer.tsx
Labels: design

#72 design : bottom sheet 위치 fix
  src/components/BottomSheet/style.ts
  src/components/BottomSheetContents/style.ts
  src/components/common/Wrapper/style.ts
  src/constant/bottomSheetPosition.ts
Labels: design

#74 feat : filteringButton 마우스로 스크롤 이벤트 추가
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetContents/style.ts
  src/components/FilterWrapper/index.tsx
  src/components/FilterWrapper/style.ts
  src/constant/filterButtonTitle.ts
  src/utils/commonUtils.ts
Labels: feat

#78 design : emergencyPage 헤더 디자인 및 기능 구현
  src/components/EmergencyHeader/index.tsx
  src/components/EmergencyHeader/style.ts
  src/components/ReportList/index.tsx
  src/hooks/useFilteringMarker.ts
  src/pages/EmergencyPage.tsx
Labels: feat

#80 feat: 경유지 위험 지표 점수 레이더 차트로 시각화
  package-lock.json
  package.json
  src/components/Chart/index.tsx
  src/components/Chart/style.ts
  src/pages/DetailRoute.tsx
  src/pages/RouteExplorer.tsx
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: design, feat

#82 feat: 경유지 위험 점수에 따라 마커 투명도 조절
  src/assets/images/ep.png
  src/assets/images/pp.png
  src/assets/images/pp1.png
  src/assets/images/pp2.png
  src/assets/images/pp3.png
  src/assets/images/pp4.png
  src/assets/images/pp5.png
  src/assets/images/sp.png
  src/components/Chart/style.ts
  src/components/ReportButton/index.tsx
  src/components/ReportButton/style.ts
  src/pages/DetailRoute.tsx
  src/utils/mapUtils.ts
Labels: design, feat

#84 design: 길찾기 버튼 디자인
  .eslintrc.json
  src/components/Search/index.tsx
  src/components/Search/style.ts
  src/pages/Home.tsx
Labels: design

#85 feat : 신고 기능 API 연결 및 Tanstack Query 적용
  src/App.tsx
  src/api/reportAPI.ts
  src/components/BottomSheetContents/index.tsx
  src/components/Chart/style.ts
  src/components/ReportButton/index.tsx
  src/components/ReportList/index.tsx
  src/components/ReportList/style.ts
  src/hooks/useEmergencyMarker.ts
  src/pages/DetailRoute.tsx
  src/pages/Report.tsx
  src/types/reportTypes.ts
  src/utils/commonUtils.ts
Labels: feat

#87 feat: 경로 내 위험 경유지 받아오는 api 연결
  src/api/routeAPI.ts
  src/components/Chart/index.tsx
  src/components/Chart/style.ts
  src/pages/DetailRoute.tsx
  src/pages/RouteExplorer.tsx
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: feat

#90 feat: 도착지 선택시 지도중심 옮기고 마커 표시
  src/components/RouteCarousel/style.ts
  src/components/Search/index.tsx
  src/pages/DetailRoute.tsx
  src/pages/Home.tsx
  src/pages/RouteExplorer.tsx
Labels: feat

#92 design : 모든 페이지 반응형 design 추가
  public/index.html
  src/components/BottomSheet/style.ts
  src/components/FilterWrapper/style.ts
  src/components/RouteCarousel/style.ts
  src/components/Search/style.ts
  src/components/common/Wrapper/index.tsx
  src/components/common/Wrapper/style.ts
  src/constant/device.ts
  src/hooks/useBottomSheet.ts
Labels: design

#95 fix : 필터링 버그 수정
  public/index.html
  src/hooks/useFilteringMarker.ts
  src/hooks/useFilteringMarkerTest.ts
Labels: fix

#98 refactor: 필터링 최적화 및 필터링 누른 채 신고 페이지 넘어갈 때 생기는 에러 해결
  src/hooks/useFilteringMarker.ts
  src/pages/Home.tsx
  src/pages/Report.tsx
Labels: fix, refactor

#99 feat : 신고할 때 내용 넣는 Modal 만들기
  src/components/ModalContents/ReportModal/index.tsx
  src/components/ModalContents/ReportModal/style.ts
  src/components/ReportButton/index.tsx
  src/components/ReportButton/style.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/pages/DetailRoute.tsx
Labels: feat

#102 design: 경로 찾기 api 응답 기다리는 동안 스켈레톤 UI 표시
  src/components/Skeleton/index.tsx
  src/components/Skeleton/style.ts
  src/pages/RouteExplorer.tsx
Labels: design

#104 refactor: 장소 검색 시 debounce로 불필요한 api 요청 줄임
  src/hooks/usePlaceSearch.ts
Labels: refactor

#105 feat : Chart에 텍스트 및 점수 추가
  src/components/Chart/index.tsx
  src/components/Chart/style.ts
  src/pages/DetailRoute.tsx
  src/utils/mapUtils.ts
Labels: design, feat

#108 feat : 신고 기능 및 UI 추가
  src/components/ModalContents/ReportModal/index.tsx
  src/components/ModalContents/ReportModal/style.ts
  src/hooks/useEmergencyMarker.ts
  src/types/reportTypes.ts
  src/utils/commonUtils.ts
  src/utils/mapUtils.ts
Labels: feat

#110 feat: 출도착지 현위치로 선택 기능 추가 및 경유지가 없는 경우 예외처리
  src/api/routeAPI.ts
  src/components/Chart/index.tsx
  src/components/Search/index.tsx
  src/components/Skeleton/index.tsx
  src/components/Skeleton/style.ts
  src/pages/DetailRoute.tsx
  src/pages/RouteExplorer.tsx
  src/recoil/atoms.ts
  src/utils/mapUtils.ts
Labels: feat, fix

#113 fix: 페이지 변경되면 시작점이 현위치로 바뀌는 버그 해결
  src/components/Search/index.tsx
  src/pages/DetailRoute.tsx
  src/pages/Home.tsx
  src/pages/RouteExplorer.tsx
  src/recoil/atoms.ts
  src/utils/mapUtils.ts
Labels: fix

#114 refactor : infoWindow의 contents를 호출하는 쪽에서 결정하도록 리팩터링
  src/hooks/useEmergencyMarker.ts
  src/utils/mapUtils.ts
Labels: refactor

#115 refactor : 이전 작업에서 있었던 TODO 제거
  src/components/Chart/index.tsx
  src/components/ModalContents/ReportModal/index.tsx
  src/pages/DetailRoute.tsx
Labels: fix, refactor

#121 design: 클릭할 수 있는 컴포넌트 인터렉션 추가, 내위치 버튼 UI 구현
  src/assets/images/near_me.png
  src/components/ModalContents/ReportModal/style.ts
  src/components/ReportButton/style.ts
  src/components/RouteCarousel/style.ts
  src/components/Search/index.tsx
  src/components/Search/style.ts
  src/pages/RouteExplorer.tsx
  src/utils/mapUtils.ts
Labels: design

#124 fix : API https 변경사항 수정 및 API 분리
  src/api/positionAPI.ts
  src/api/reportAPI.ts
  src/hooks/useFilteringMarker.ts
Labels: fix
