Repository Seoul-Public-Data/seoul_frontend, pull requests merged in 2024-05, with the labels that each got.

#126 feat: 현위치 추적 기능 추가, 경로 페이지에 안전시설 마커 추가, 체크박스 스타일링
  src/assets/images/check.png
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetContents/style.ts
  src/hooks/useCurruntPosition.ts
  src/hooks/useFilteringMarker.ts
  src/hooks/useRandom.ts
  src/pages/DetailRoute.tsx
  src/pages/Home.tsx
  src/pages/RouteExplorer.tsx
Labels: design, feat

#128 chore : PWA 배포 관련 설정
  public/favicon.ico
  public/icons/apple-touch-icon-114x114.png
  public/icons/apple-touch-icon-120x120.png
  public/icons/apple-touch-icon-144x144.png
  public/icons/apple-touch-icon-152x152.png
  public/icons/apple-touch-icon-57x57.png
  public/icons/apple-touch-icon-60x60.png
  public/icons/apple-touch-icon-72x72.png
  public/icons/apple-touch-icon-76x76.png
  public/icons/favicon-128.png
  public/icons/favicon-16x16.png
  public/icons/favicon-196x196.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/icons/mstile-144x144.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/index.html
  public/manifest.json
Labels: chore

#130 feat: 404 에러 페이지 추가
  src/App.tsx
  src/assets/images/logo.png
  src/components/Chart/index.tsx
  src/components/FilterWrapper/style.ts
  src/components/NotFound/index.tsx
  src/components/NotFound/style.ts
  src/pages/RouteExplorer.tsx
  src/utils/mapUtils.ts
Labels: design, feat

#131 design : 폰트 추가 및 적용
  declarations.d.ts
  public/index.html
  public/manifest.json
  src/App.tsx
  src/fonts/NotoSans-Bold.woff
  src/fonts/NotoSans-Regular.woff
  src/styles/GlobalStyles.ts
  src/styles/fonts.ts
  tsconfig.json
Labels: design

#133 fix : Tmap 에러 픽스(Mixed Contents 에러)
  public/index.html
Labels: fix

#134 design: font Pretendard로 수정 및 Chart width 수정
  src/components/Chart/index.tsx
  src/fonts/NotoSans-Bold.woff
  src/fonts/NotoSans-Regular.woff
  src/fonts/Pretendard-Bold.subset.woff
  src/fonts/Pretendard-Regular.subset.woff
  src/styles/GlobalStyles.ts
  src/styles/fonts.ts
Labels: design

#137 fix : http로 요청 변경 및 meta태그 제거
  public/index.html
  src/api/positionAPI.ts
Labels: fix

#138 fix: https로 요청 변경
  src/api/positionAPI.ts
  src/api/reportAPI.ts
  src/hooks/useCurruntPosition.ts
Labels: fix

#142 feat: 위험지표에 인구밀도 점수 추가
  src/types/mapTypes.ts
  src/utils/mapUtils.ts
Labels: feat

#145 test : cypress를 위한 기본 설정 및 간단한 homepage test 구현
  cypress.config.ts
  cypress/e2e/1.homePage/homepage.cy.ts
  cypress/fixtures/getCCTV.json
  cypress/fixtures/getEmergencyBell.json
  cypress/fixtures/getFireStation.json
  cypress/fixtures/getHeatShelter.json
  cypress/fixtures/getReport.json
  cypress/fixtures/getSafetyCenter.json
  cypress/fixtures/getSafetyFacility.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/components/BottomSheetContents/index.tsx
  src/components/BottomSheetHeader/index.tsx
  src/components/FilterWrapper/index.tsx
  src/components/Search/index.tsx
  tsconfig.json
Labels: test
